plugin: aws_ec2
regions: 
  - eu-central-1
aws_access_key: ""
aws_secret_key: ""
hostnames:
  - tag:name
  - network-interface.addresses.association.public-ip
    
compose:
  ansible_host: public_ip_address

keyed_groups:
  - prefix: tag
    key: tags

groups:
  "iperfserver": 'tags.iperf=="true"'
  "psqlserver": 'tags.psql=="true"'
  "benchmark": 'tags.testing=="true"'
  "has_gpu": "tags.gpu=='true'"
